services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - .env.example:/var/www/html/.env
    networks:
      - custom_network
    depends_on:
      - db
    environment:
      - UID=1000
      - GID=1000
  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   container_name: client
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/app
  #     - ./client/.env.sample:/app/.env
  #   networks:
  #     - custom_network
  #   depends_on:
  #     - server
  #   command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
  #   restart: always
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'backend_olx'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - './mysql_data:/var/lib/mysql'
    networks:
      - custom_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8001:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - custom_network
networks:
  custom_network:
    driver: bridge 